repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        pass_filenames: false
        entry: just lint
        stages: [pre-commit]

      - id: test
        name: test
        language: system
        pass_filenames: false
        entry: just test
        stages: [pre-commit]
