[project]

use_directory_urls = false

site_name = "satterc"
site_description = "A Python framework for data-driven terrestrial carbon modelling based on Directed Acyclic Graphs."
site_author = "Joe Marsh Rossney"
site_url = "https://satterc.github.io/satterc"

repo_name = "SatTerC/satterc"
repo_url = "https://github.com/SatTerC/satterc"

copyright = "Copyright &copy; 2026 The authors"

nav = [
  { "Home" = "index.md" },
  { "Getting Started" = [
      "Getting Started/installation.md",
      "Getting Started/quickstart.md",
      "Getting Started/concepts.md",
  ]},
  { "Usage" = [
      "Usage/config.md",
      "Usage/cli.md",
      "Usage/data-formats.md",
      "Usage/custom-modules.md",
      "Usage/troubleshooting.md",
  ]},
  { "Models" = [
      "Models/index.md",
      "Models/splash.md",
      "Models/pmodel.md",
      "Models/sgam.md",
      "Models/rothc.md",
  ]},
  { "Examples" = [
      "Examples/my_first_pipeline.md",
      "Examples/soil_moisture.md",
      "Examples/pft_parameters.md",
      "Examples/full_pipeline.md",
  ]},
  { "API Reference" = [
      "API/satterc.pipeline/satterc.pipeline.inputs/daily.md",
      "API/satterc.pipeline/satterc.pipeline.inputs/weekly.md",
      "API/satterc.pipeline/satterc.pipeline.inputs/monthly.md",
      "API/satterc.pipeline/satterc.pipeline.inputs/static.md",
      "API/satterc.pipeline/satterc.pipeline.models/splash.md",
      "API/satterc.pipeline/satterc.pipeline.models/pmodel.md",
      "API/satterc.pipeline/satterc.pipeline.models/sgam.md",
      "API/satterc.pipeline/satterc.pipeline.models/rothc.md",
      "API/satterc.pipeline/grid.md",
      "API/satterc.pipeline/resample.md",
      "API/satterc.pipeline/pipeline.outputs/daily.md",
      "API/satterc.pipeline/pipeline.outputs/weekly.md",
      "API/satterc.pipeline/pipeline.outputs/monthly.md",
      "API/satterc.pipeline/pipeline.outputs/static.md",
  ]},
  { "CLI Reference" = [
      "CLI Reference/index.md",
      "CLI Reference/cli.md",
      "CLI Reference/graph.md",
      "CLI Reference/run.md",
      "CLI Reference/setup.md",
      "CLI Reference/data_gen.md",
      "CLI Reference/version.md",
  ]},
]

# Katex
extra_javascript = [
    "javascripts/marimo-button.js",
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]
extra_css = [
    "https://unpkg.com/katex@0/dist/katex.min.css"
]

[project.theme]
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/moon"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/sun"
toggle.name = "Switch to light mode"


# Extensions
# ----------
# https://zensical.org/docs/setup/extensions/

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]

# Mkdocstrings
# ------------

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
annotations_path = "brief"
docstring_style = "numpy"
docstring_section_style = "list"
inherited_members = true
line_length = 88
merge_init_into_class = true
separate_signature = true
show_signature = true
signature_crossrefs = true
show_signature_annotations = true
show_if_no_docstring = false
show_root_full_path = true
show_root_heading = true
show_root_members_full_path = false
show_source = false
show_symbol_type_heading = true
show_symbol_type_toc = true

