modules = [
  "models.pmodel",
  "models.splash",
  "models.sgam",
  "models.rothc",
  "inputs.daily",
  "inputs.weekly",
  "inputs.monthly",
  "inputs.static",
  "resample",
  "outputs.daily",
  "outputs.weekly",
  "outputs.monthly",
]

[extra_config]
n_years_spinup = 1

[models.pmodel]
method_kphio = "sandoval"
method_optchi = "lavergne20_c3"

[inputs.daily]
path = "data/daily.nc"
vars = [
  "precipitation_mm",
  "sunshine_fraction",
  "temperature_celcius",
  "lai",
  "gpp",
]

[inputs.weekly]
path = "data/weekly.nc"
vars = [
  "co2_ppm",
  "fapar",
  "ppfd_umol_m2_s1",
  "pressure_pa",
  "vpd_pa",
]

[inputs.monthly]
path = "data/monthly.nc"
vars = [
  "dummy_variable",
]

[inputs.static]
path = "data/static.nc"
vars = [
  "elevation",
  "plant_type",
  "max_soil_moisture",
  "clay_content",
  "soil_depth",
  "organic_carbon_stocks",
  "root_pool_init",
  "leaf_pool_init",
  "stem_pool_init",
]

[resample]
daily_to_weekly = [
  "temperature_celcius",
  "precipitation_mm",
  "soil_moisture",
  "aridity_index",
]

daily_to_monthly = [
  "temperature_celcius",
  "precipitation_mm",
  "actual_evapotranspiration",
]

weekly_to_monthly = [
  "litter_pool",
]

[outputs.daily]
path = "results/daily.nc"
vars = [
  "actual_evapotranspiration",
  "soil_moisture",
  "runoff",
]

[outputs.weekly]
path = "results/weekly.nc"
vars = [
  "gpp",
  "leaf_pool",
  "stem_pool",
  "root_pool",
  "litter_pool",
  "leaf_area_index",
]

[outputs.monthly]
path = "results/monthly.nc"
vars = [
  "decomposable_plant_material",
  "resistant_plant_material",
  "microbial_biomass",
  "humified_organic_matter",
  "soil_organic_carbon",
]
