# NOTE: these commands assume you have activated the Python virtual environment
# using `source .venv/bin/activate`. If your workflow doesn't include this, you
# can redefine 'prefix' to prepend 'uv run' to the commands.

prefix := "" # switch to "uv run" if required
alias run := export

# Default recipe to display available commands.
_:
  @just --list

# Opens notebook.py in editable mode using the marimo browser interface.
[no-cd]
edit:
  {{prefix}} marimo edit notebook.py

# Runs notebook.py as a python script and exports the result to notebook.html.
[no-cd]
export: lint md
  {{prefix}} marimo export html notebook.py --output notebook.html --force

# Generates a PDF visualisation of the DAG (requires graphviz to be installed).
[no-cd]
graph:
  {{prefix}} satterc graph config.toml --pdf
  rm pipeline.dot

# Converts notebook.py to a markdown document.
[no-cd]
md:
  {{prefix}} marimo export md notebook.py --output notebook.md --force
  printf '\n---\n\n<a href="notebook.html" class="md-button md-button--primary">Open Marimo notebook</a>\n' >> notebook.md

# Runs ruff and marimo linters, and ruff formatter.
[no-cd]
lint:
  {{prefix}} ruff check notebook.py
  {{prefix}} ruff format notebook.py
  {{prefix}} marimo check notebook.py

# Opens notebook.py in read-only mode using the marimo browser interface.
[no-cd]
read:
  {{prefix}} marimo run notebook.py

# Hidden recipe used by pre-commit hook. Runs 'lint' and 'md' in notebooks/{{experiment}}
_precommit experiment:
  cd notebooks/{{experiment}} && just lint md && cd {{justfile_directory()}}
