# Default recipe to display available commands.
_:
  @just --list

# Opens notebook.py in editable mode using the marimo browser interface.
[default]
edit:
  marimo edit notebook.py

# Runs ruff and marimo linters, and ruff formatter.
[no-cd]
lint:
  ruff check notebook.py
  ruff format notebook.py
  marimo check notebook.py

