[splash]
    _import_path = "satterc.models.splash"

    [inputs.daily]
    path = "daily.csv"
    vars = [
      "precipitation",
      "sunshine_fraction",
      "temperature",
    ]

    [inputs.static]
    path = "static.json"
    suffix = ""
    vars = [
      "elevation",
      "latitude",
      "max_soil_moisture",
    ]

    [outputs.daily]
    path = "results/daily.csv"
    vars = [
      "actual_evapotranspiration",
      "soil_moisture",
      "runoff",
    ]
