"""The vocabulary in which synthetic variables are described.

A synthetic variable is one `Var` in a table: units, a long name, and a single
generator lambda. Everything mechanical — grid geometry, array shapes,
coordinates, clipping to physical bounds, dtype, and resolving one variable's
dependency on another — lives here, so supporting a new model's inputs means
adding rows to the tables in `satterc.setup_utils.data_gen.daily` /
`.static` rather than writing a generator function per variable.

The generator is called with a context (`DailyCtx` or `StaticCtx`) that carries
the grid and the random-draw helpers, and knows the shape the variable should
have. A daily generator therefore returns ``(n_days, n_pixels)`` and a static one
``(n_pixels,)``, but neither has to say so: anything broadcastable to that shape
is accepted, so a spatially uniform variable can return a ``(n_days, 1)`` column
and a constant can return a scalar.
"""

import logging
import zlib
from collections.abc import Callable
from dataclasses import dataclass
from types import ModuleType
from typing import Any

import numpy as np
import pandas as pd
import xarray as xr
from numpy.typing import DTypeLike, NDArray

logger = logging.getLogger(__name__)

#: Length of the seasonal cycle in days.
DAYS_PER_YEAR = 365.25

_DEFAULT_START_DATE = "2020-01-01"
_LAT_RANGE = (50.0, 54.0)
_LON_RANGE = (-4.0, 2.0)


@dataclass(frozen=True)
class Var:
    """A synthetic variable: metadata plus one generator.

    Attributes
    ----------
    units : str
        CF-style unit string, written to the file as the ``units`` attribute.
    long_name : str
        Human-readable name, written as the ``long_name`` attribute.
    gen : Callable
        Called with a `DailyCtx` or `StaticCtx` and returning anything
        broadcastable to that context's shape.
    bounds : tuple
        ``(lower, upper)`` clip applied to the generated values, either of which
        may be ``None``. This is the place to state a variable's physical range —
        non-negative precipitation, a 0-1 fraction — rather than clipping inside
        ``gen``.
    dtype : DTypeLike
        dtype of the stored values. Only needs setting for integer-valued
        variables such as class labels.
    """

    units: str
    long_name: str
    gen: Callable[[Any], Any]
    bounds: tuple[float | None, float | None] = (None, None)
    dtype: DTypeLike = np.float64


def collect_vars(module: ModuleType) -> dict[str, Var]:
    """Collect a table module's `Var` constants, keyed by name in source order.

    Each variable is a module-level constant rather than a dict entry so that it
    carries a real docstring, which mkdocstrings renders alongside the generator
    source without any help. This turns that back into the mapping `Resolver`
    wants. Names are therefore Python identifiers; a file variable whose name is
    not one can only be generated by the fallback.
    """
    return {
        name: value
        for name, value in vars(module).items()
        if isinstance(value, Var) and not name.startswith("_")
    }


def smooth2d(arr: NDArray[np.float64], radius: int) -> NDArray[np.float64]:
    """Box-filter smooth a 2D array, reflecting at boundaries."""
    if radius <= 0 or min(arr.shape) <= 1:
        return arr
    ny, nx = arr.shape
    out = np.zeros_like(arr, dtype=float)
    for di in range(-radius, radius + 1):
        rows = np.clip(np.arange(ny) + di, 0, ny - 1)
        for dj in range(-radius, radius + 1):
            cols = np.clip(np.arange(nx) + dj, 0, nx - 1)
            out += arr[np.ix_(rows, cols)]
    return out / (2 * radius + 1) ** 2


class Grid:
    """The lat/lon grid and time axis the synthetic data is generated on.

    Pixels are the cartesian product of the latitude and longitude points,
    flattened into conduit's ``pixel`` dimension in row-major order, so ``lat``
    and ``lon`` are per-pixel arrays rather than axes.
    """

    def __init__(
        self,
        n_lat: int,
        n_lon: int,
        n_days: int,
        start_date: str = _DEFAULT_START_DATE,
    ) -> None:
        self.n_lat = n_lat
        self.n_lon = n_lon
        self.n_days = n_days
        self.n_pixels = n_lat * n_lon

        self.time_coord = np.datetime64(start_date) + np.arange(n_days)

        lat_grid, lon_grid = np.meshgrid(
            np.linspace(*_LAT_RANGE, n_lat),
            np.linspace(*_LON_RANGE, n_lon),
            indexing="ij",
        )
        self.lat: NDArray[np.float64] = lat_grid.ravel()
        self.lon: NDArray[np.float64] = lon_grid.ravel()
        self.pixel_coords = pd.MultiIndex.from_arrays(
            [self.lat, self.lon], names=["y", "x"]
        )


class _Ctx:
    """What a generator lambda is handed: the grid, plus shaped random draws.

    The random helpers all draw at the context's own shape, which is what lets
    the same expression serve a daily and a static variable.
    """

    def __init__(self, resolver: "Resolver", rng: np.random.Generator) -> None:
        self._resolver = resolver
        self.grid = resolver.grid
        self.rng = rng
        """This variable's own random stream. Use it for any draw the helpers
        below do not cover, so that the variable stays independent of the rest."""

    @property
    def shape(self) -> tuple[int, ...]:
        raise NotImplementedError

    @property
    def lat(self) -> NDArray[np.float64]:
        """Latitude of each pixel, shape ``(n_pixels,)``."""
        return self.grid.lat

    @property
    def lon(self) -> NDArray[np.float64]:
        """Longitude of each pixel, shape ``(n_pixels,)``."""
        return self.grid.lon

    @property
    def n_pixels(self) -> int:
        return self.grid.n_pixels

    @property
    def n_days(self) -> int:
        return self.grid.n_days

    def static(self, name: str) -> NDArray[np.float64]:
        """Values of another static variable, shape ``(n_pixels,)``."""
        return self._resolver.static(name).values

    def uniform(self, low: float, high: float) -> NDArray[np.float64]:
        return self.rng.uniform(low, high, self.shape)

    def normal(self, loc: float, scale: float) -> NDArray[np.float64]:
        return self.rng.normal(loc, scale, self.shape)

    def integers(self, low: int, high: int) -> NDArray[np.float64]:
        """Integers drawn uniformly from ``[low, high)``, as floats."""
        return self.rng.integers(low, high, self.shape).astype(float)


class StaticCtx(_Ctx):
    """Context for a time-invariant variable, shape ``(n_pixels,)``."""

    @property
    def shape(self) -> tuple[int, ...]:
        """Shape of a static field: ``(n_pixels,)``."""
        return (self.grid.n_pixels,)

    def smooth_noise(self, scale: float) -> NDArray[np.float64]:
        """Spatially coherent noise: Gaussian draws run through a box filter.

        Smoothing over a fraction of the grid gives neighbouring pixels similar
        values, so fields like elevation vary smoothly rather than per-pixel.
        """
        noise = self.rng.normal(0.0, scale, (self.grid.n_lat, self.grid.n_lon))
        radius = max(1, min(self.grid.n_lat, self.grid.n_lon) // 3)
        return smooth2d(noise, radius).ravel()


class DailyCtx(_Ctx):
    """Context for a time-varying variable, shape ``(n_days, n_pixels)``.

    The time-axis helpers (`day`, `doy`, `cycle`, `ar1`) return column vectors of
    shape ``(n_days, 1)``, so combining them with the per-pixel `lat` / `lon`
    arrays broadcasts to the full field without any explicit reshaping.
    """

    @property
    def shape(self) -> tuple[int, ...]:
        """Shape of a daily field: ``(n_days, n_pixels)``."""
        return (self.grid.n_days, self.grid.n_pixels)

    @property
    def day(self) -> NDArray[np.float64]:
        """Days since the start of the run, shape ``(n_days, 1)``."""
        return np.arange(self.grid.n_days, dtype=float)[:, np.newaxis]

    @property
    def doy(self) -> NDArray[np.float64]:
        """Day of year, shape ``(n_days, 1)``."""
        return self.day % DAYS_PER_YEAR

    def daily(self, name: str) -> NDArray[np.float64]:
        """Values of another daily variable, shape ``(n_days, n_pixels)``."""
        return self._resolver.daily(name).values

    def cycle(
        self, amplitude: float, phase: float = 0.0, baseline: float = 0.0
    ) -> NDArray[np.float64]:
        """Return a one-year sinusoid, shape ``(n_days, 1)``.

        ``phase`` shifts the peak: the default puts it a quarter-year in, and
        ``-pi / 2`` puts it mid-year, which is what a northern-hemisphere summer
        peak wants.
        """
        return baseline + amplitude * np.sin(
            2 * np.pi * self.day / DAYS_PER_YEAR + phase
        )

    def ar1(self, sigma: float, phi: float = 0.7) -> NDArray[np.float64]:
        """AR(1) noise: ``noise[t] = phi * noise[t-1] + innovation[t]``.

        The innovation variance is scaled so the stationary marginal standard
        deviation equals ``sigma``. Pixels are independent, but each has temporal
        autocorrelation ``phi`` — weather is correlated day to day, and models
        that integrate state respond quite differently to white noise.
        """
        n_days, n_pixels = self.shape
        innovation_std = sigma * np.sqrt(1.0 - phi**2)
        noise = np.empty((n_days, n_pixels))
        noise[0] = self.rng.normal(0.0, sigma, n_pixels)
        for t in range(1, n_days):
            noise[t] = phi * noise[t - 1] + self.rng.normal(
                0.0, innovation_std, n_pixels
            )
        return noise


class Resolver:
    """Turn variable names into `xarray.DataArray` objects, on demand.

    Results are memoised, so a variable used as a dependency by several others
    (elevation, temperature) is generated once and every consumer sees the same
    field. A name absent from the tables is passed to ``fallback``, which
    invents a plausible `Var` from the name alone.
    """

    def __init__(
        self,
        grid: Grid,
        daily_vars: dict[str, Var],
        static_vars: dict[str, Var],
        fallback: Callable[[str], Var],
        seed: int = 42,
    ) -> None:
        self.grid = grid
        self.seed = seed
        self._tables = {"daily": daily_vars, "static": static_vars}
        self._fallback = fallback
        self._cache: dict[tuple[str, str], xr.DataArray] = {}
        self._resolving: set[tuple[str, str]] = set()

    def daily(self, name: str) -> xr.DataArray:
        """Generate (or return the cached) daily variable ``name``."""
        return self._resolve(name, "daily")

    def static(self, name: str) -> xr.DataArray:
        """Generate (or return the cached) static variable ``name``."""
        return self._resolve(name, "static")

    def _resolve(self, name: str, kind: str) -> xr.DataArray:
        key = (kind, name)
        if key in self._cache:
            return self._cache[key]
        if key in self._resolving:
            raise ValueError(
                f"Circular dependency while generating {kind} variable '{name}'."
            )

        self._resolving.add(key)
        try:
            var = self._tables[kind].get(name) or self._fallback(name)
            rng = self._rng_for(kind, name)
            ctx = DailyCtx(self, rng) if kind == "daily" else StaticCtx(self, rng)
            result = self._build(name, var, ctx)
        finally:
            self._resolving.discard(key)

        self._cache[key] = result
        return result

    def _rng_for(self, kind: str, name: str) -> np.random.Generator:
        """Build a stream of this variable's own, from the seed and its name.

        Deriving from the name rather than drawing from one shared stream means a
        variable's values do not depend on which *other* variables were asked
        for, or in what order. Two configs requesting different sets agree on the
        ones they share, and one input file can be regenerated without disturbing
        the rest. `zlib.crc32` because `hash` is salted per process.
        """
        return np.random.default_rng([self.seed, zlib.crc32(f"{kind}:{name}".encode())])

    def _build(self, name: str, var: Var, ctx: _Ctx) -> xr.DataArray:
        values = np.broadcast_to(np.asarray(var.gen(ctx), dtype=float), ctx.shape)
        low, high = var.bounds
        if low is not None or high is not None:
            values = np.clip(values, low, high)
        # Always copies, so no consumer holds a read-only broadcast view.
        values = np.array(values, dtype=var.dtype)

        attrs = {"units": var.units, "long_name": var.long_name}
        if isinstance(ctx, DailyCtx):
            return xr.DataArray(
                data=values,
                dims=["time", "pixel"],
                coords={
                    "time": self.grid.time_coord,
                    "pixel": self.grid.pixel_coords,
                },
                attrs=attrs,
                name=name,
            )
        return xr.DataArray(
            data=values,
            dims=["pixel"],
            coords={"pixel": self.grid.pixel_coords},
            attrs=attrs,
            name=name,
        )
