name: Documentation
on:
  push:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --dev

      - name: Export the examples
        run: uv run just export-all

      - name: Build the documentation
        run: uv run just docs

      - name: Upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4
